name: Deploy

on:
  push:
    branches: [ master ]

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Fly
        run: |
          curl -L https://fly.io/install.sh | sh
      - name: Verify Fly is installed
        run: |
          fly version
      - name: Login to Fly
        run: |
          fly auth docker --access-token "$TOKEN"
      - name: Deploy to Fly
        run: |
          bash scripts/deploy.sh
        env:
          MACHINE_ID: ${{ secrets.MACHINE_ID }}
